version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.6.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install
  test:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout

      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "f3:37:ee:01:51:5b:63:81:61:9f:82:d9:8f:2c:cf:ab"

      - run: git config core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

      - run: git remote add dokku dokku@stacket.io:website

      - run: git push dokku master

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - deploy
#      - build
#      - test:
#          requires:
#            - build
#      - deploy:
#          requires:
#            - test
#          filters:
#            branches:
#              only: master
