version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.6.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install
  test:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout

      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "12:7e:0a:bb:c1:96:c0:0e:46:13:6f:49:86:79:81:d6"

      - run: git remote add dokku dokku@stacket.io:website

      - run: git push dokku master

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
