version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          command: npm test
  deploy:
    docker:
      - image: circleci/node:4.8.2-jessie
      steps:
        - checkout
        - run:
            command: npm test
    branches:
      only:
        - master
        - git remote add dokku dokku@stacket.io:website
        - git push dokku master

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - build
      - test:
          - requires:
              - build
      - deploy:
          - requires:
              - test
          - filters:
            branches:
              only: master
