version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.6.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install
  test:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout

      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "56:09:98:2e:b6:04:95:0a:23:df:54:a6:ec:ba:82:83"

      - run: git remote add dokku dokku@stacket.io:website

      - run: git push dokku master

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - deploy
#      - build
#      - test:
#          requires:
#            - build
#      - deploy:
#          requires:
#            - test
#          filters:
#            branches:
#              only: master
